volumes:
  postgres_data:
      driver: local

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - app-network    
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start
      - --import-realm
    volumes:
      - ./config/:/opt/keycloak/data/import/
    depends_on:
      - postgres
    networks:
      - app-network
      
  mailhog-keycloak:
        image: mailhog/mailhog
        container_name: mailhog
        logging:
          driver: 'none'  
        ports:
          - 1025:1025 
          - 8025:8025 
        networks:
           - app-network
      
networks:
  app-network:
    driver: bridge
